GET http://localhost:3000/api/users HTTP/1.1 // สั่งยิงคำขอแบบ GET ไปที่ช่องทางดึงข้อมูลผู้ใช้ทั้งหมด เพื่อทดสอบระบบ
Content-Type: application/json               // บอกเซิร์ฟเวอร์ว่า แพ็กเกจพัสดุที่จะแนบไปถัดจากนี้จะมาในรูปแบบก้อน JSON นะ

{                                            // เปิดก้อนพัสดุเปล่า (ส่งแบบไม่มีเนื้อหาข้างใน เพราะคำสั่ง GET มักไม่ส่งเนื้อหา)

}                                            // ปิดก้อนพัสดุ

###                                          // เครื่องหมายสามขีด เอาไว้ใช้ตัดแบ่งช่อง แบ่งเส้นทางแต่ละข้อออกจากกัน เพื่อความเป็นระเบียบ
POST http://localhost:3000/api/multiple_by_2 HTTP/1.1 // สั่งยิงคำขอแบบ POST (ส่งของหนัก) ไปที่ช่องทางคำนวณคณิตศาสตร์คูณสอง
Content-Type: application/json               // แจ้งเซิร์ฟเวอร์หลังบ้านว่า ของที่อยู่ข้างล่างนี้จะส่งไปในรูปแบบ JSON นะ

{                                            // เปิดกล่องส่งของเพื่อยัดตัวเลขที่จะเอาไปให้หลังบ้านคำนวณ
    "no_1": 5,                               // แนบตัวเลขตัวที่หนึ่งไปคือเลข 5 (หลังบ้านจะเอาไปคูณสอง ได้ผลลัพธ์กลับมาเป็น 10)
    "no_2": 10                               // แนบตัวเลขตัวที่สองไปคือเลข 10 (หลังบ้านจะเอาไปคูณสอง ได้ผลลัพธ์กลับมาเป็น 20)
}                                            // ปิดกล่องส่งของ


###                                          // เส้นตัดแบ่งช่อง เพื่อเริ่มต้นคำสั่งทดสอบใหม่อีกข้อหนึ่ง
GET http://localhost:3000/api/user/1 HTTP/1.1 // สั่งยิงคำขอแบบ GET ไปขอดูดหน้าโปรไฟล์ผู้ใช้เฉพาะคน โดยระบุเจาะจงเลยว่าเป็นผู้ใช้ไอดีเลข 1
Content-Type: application/json               // แจ้งบอกประเภทข้อมูลที่จะคุยกันว่าเป็นแบบ JSON สากลทั่วไป